# Site settings
title: Dr Lam - Web Developer
description: "A blog about Ban Lam De Thuong ..."
baseurl:
url: "imhereifyouwant.github.io"

# User settings
username: Ban Lam De Thuong
user_title: Lorem Ipsum - FrontEnd
email: imhereifyouwant@gmail.com
twitter_username: imhereifyouwant
github_username:  imhereifyouwant
gplus_username:  imhereifyouwant
linkedin_public_url: 
disqus_username: imhereifyouwant
profile_picture:
